apiVersion: rrsd.zetaapps.in/v1alpha1
kind: EmeraldClosurePolicy 
metadata:
  name: lsg.emerald.emeraldclosurepolicy.9001
spec:
  metadata:
    id: emerald.emeraldclosurepolicy.9001
    name: Emerald Closure Policy - Credit Line on UPI 
    description: Emerald Closure Policy for Credit Line on UPI product
    requester:
      module: emerald-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  validFrom: '2026-01-01T00:00:00.000+05:30'
  validTill: '2999-12-31T00:00:00.000+05:30'
  name: Emerald Closure Policy - Credit Line on UPI 
  description: Emerald Closure Policy for Credit Line on UPI product
  code: ECPIN009001
  allowCancellation: true  
  coolingPeriodForCancellation: 30
  allowPreClosure: true
  preClosureLockIn: 0  
  autoPreClosureThresholdPercentage: 97.99 #additional
  includeCatchUpInterest: false #additional
  templateCode: in-credit
