kind: Configuration
apiVersion: rrsd.zetaapps.in/v1alpha1
metadata:
  name: lsg.ruby.configuration.module.clou-upi-interest-program.interest-program
  labels:
    rrsd.zetaapps.in/day: day-zero
  namespace: ruby
  annotations:
    zeta.tech/resource-tags: '{"gitDbRepo":"tenant_configuration.aws-clou-upi-pp-mumbai.lsg","gitDbPath":"https://gitea.internal.mum1-pp.zetaapps.in/zetaengg/tenant_configuration.aws-clou-upi-pp-mumbai.lsg.git","filePath":"/.clou-upis/module_configurations/module_ruby/tree/root/t0/module_configurations/module_ruby/interest-programs/interest-program-clou-upi-interest-program.yaml","tenantCode":"lsg"}'
spec:
  metadata:
    id: ruby.configuration.module.clou-upi-interest-program.interest-program
    name: clou-upi credit line-interest-program
    description: ABC Bank clou-upi Credit line Interest Program
    requester:
      module: ruby
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  config:
    format: YAML
    schemaUrl: http://localhost
    schemaInlineContent: |
      {"properties":{"amountTiers":{"items":{"properties":{"fromAmount":{"type":"number"},"tenureTier":{"items":{"properties":{"fromTenure":{"properties":{"days":{"type":"number"},"months":{"type":"number"},"years":{"type":"number"}},"type":"object"},"interestRate":{"type":"number"},"toTenure":{"properties":{"days":{"type":"number"},"months":{"type":"number"},"years":{"type":"number"}},"type":"object"}},"type":"object"},"type":"array"},"toAmount":{"type":"number"}},"type":"object"},"type":"array"},"currency":{"type":"string"},"description":{"type":"string"},"name":{"type":"string"},"rateSpecificationCode":{"type":"string"},"status":{"type":"string"},"validFrom":{"type":"string"},"validTill":{"type":"string"}},"type":"object"}
    key: key
    isEncrypted: false
    useVault: false
    value:
      attributes: {}
      code: IPGIN0001
      description: clou-upi Interest Program
      interestRules:
      - applicableTo:
          maxValueThreshold: 999999999999
          minValueThreshold: 0
          postingCategories:
          - RetailPrincipalUnbilled
          transactionSelectionCriterion: function evaluate(ruleContext) { var mcc = ruleContext && ruleContext.postingInfo && ruleContext.postingInfo.postingAttributes && ruleContext.postingInfo.postingAttributes['super-card.mcc']; return ['8011','8041','8021'].indexOf(mcc) !== -1; }
        modelParameters:
          gracePeriodType: POLICY
          margin: 18.00
          maxRate: 28.00
          rateTable:
            code: IRTIN0001
            version: 1
        precedenceCode: 100
        ruleId: RULE_MEDICAL
      - applicableTo:
          maxValueThreshold: 999999999999
          minValueThreshold: 0
          postingCategories:
          - RetailPrincipalUnbilled
          transactionSelectionCriterion: function evaluate(ruleContext) { var mcc = ruleContext && ruleContext.postingInfo && ruleContext.postingInfo.postingAttributes && ruleContext.postingInfo.postingAttributes['super-card.mcc']; return ['5732','5733','5722','5211'].indexOf(mcc) !== -1; }
        modelParameters:
          gracePeriodType: POLICY
          margin: 27.00
          maxRate: 36.00
          rateTable:
            code: IRTIN0001
            version: 1
        precedenceCode: 110
        ruleId: RULE_ELECTRONICS
      - applicableTo:
          maxValueThreshold: 999999999999
          minValueThreshold: 0
          postingCategories:
          - RetailPrincipalUnbilled
          transactionSelectionCriterion: function evaluate(ruleContext) { return true; }
        modelParameters:
          gracePeriodType: POLICY
          margin: 24.00
          maxRate: 34.00
          rateTable:
            code: IRTIN0003
            version: 1
        precedenceCode: 200
        ruleId: RULE_01
      name: clou-upi Interest Program
      precedenceCode: '100'
      type: General
      validFrom: '2026-01-01T00:00:00.000+05:30'
      validUntil: '2999-12-31T23:59:59.999+05:30'
  viewConfig:
    angelosSchema:
      view: {}

