kind: RubyRepaymentPolicy
apiVersion: rrsd.zetaapps.in/v1alpha1
metadata:
  name: lsg.ruby.rubyrepaymentpolicy.module.8005
  labels:
    rrsd.zetaapps.in/day: day-zero
  annotations:
    zeta.tech/resource-tags: '{"gitDbRepo":"tenant_configuration.aws-default-pp-mumbai.lsg","gitDbPath":"https://gitea.internal.mum1-pp.zetaapps.in/zetaengg/tenant_configuration.aws-default-pp-mumbai.lsg.git","filePath":"module_configurations/module_ruby/repayment-policies/ruby-repayment-policy_8005.yaml","tenantCode":"lsg"}'
  namespace: ruby
spec:
  metadata:
    id: ruby.rubyrepaymentpolicy.module.8005
    name: ruby.rubyrepaymentpolicy.module.8005
    description: ruby.rubyrepaymentpolicy.module.8005
    tenantId: '600309'
    tenantCode: lsg
  name: Ruby Repayment Policy
  code: REPIN00001
  description: Ruby Repayment Policy
  repaymentAllocation:
    aboveMAD:
      allocationModel: HIGHESTTOLOWESTAPR
      allocationTieBreaker: REPAYMENTSEQUENCE
      repaymentSequence:
        - chargeOffStatuses:
            - '*'
          repaymentSequenceTieBreaker: FIFO
          settlementPriority:
            - LateFeeBilled
            - CollectionFeeBilled
            - RetailMiscFeeBilled
            - RetailServiceFeeBilled
            - AnnualFeeBilled
            - RetailInterestBilled
            - RetailPrincipalBilled
            - LateFeeUnbilled
            - CollectionFeeUnbilled
            - RetailMiscFeeUnbilled
            - RetailServiceFeeUnbilled
            - AnnualFeeUnbilledx
            - RetailInterestUnbilled
            - RetailPrincipalUnbilled
        - chargeOffStatuses:
            - FINAL_CHARGEOFF
          repaymentSequenceTieBreaker: FIFO
          settlementPriority:
            - RetailPrincipalBilled
            - LateFeeBilled
            - RetailMiscFeeBilled
            - RetailServiceFeeBilled
            - AnnualFeeBilled
            - RetailInterestBilled
            - RetailPrincipalUnbilled
            - LateFeeUnbilled
            - RetailMiscFeeUnbilled
            - RetailServiceFeeUnbilled
            - AnnualFeeUnbilled
            - RetailInterestUnbilled
    belowMAD:
      allocationModel: LOWESTTOHIGHESTAPR
      allocationTieBreaker: REPAYMENTSEQUENCE
      repaymentSequence:
        - chargeOffStatuses:
            - '*'
          repaymentSequenceTieBreaker: FIFO
          settlementPriority:
            - LateFeeBilled
            - RetailMiscFeeBilled
            - RetailServiceFeeBilled
            - AnnualFeeBilled
            - RetailInterestBilled
            - RetailPrincipalBilled
            - LateFeeUnbilled
            - RetailMiscFeeUnbilled
            - RetailServiceFeeUnbilled
            - AnnualFeeUnbilled
            - RetailInterestUnbilled
            - RetailPrincipalUnbilled
        - chargeOffStatuses:
            - FINAL_CHARGEOFF
          repaymentSequenceTieBreaker: FIFO
          settlementPriority:
            - RetailPrincipalBilled
            - LateFeeBilled
            - RetailMiscFeeBilled
            - RetailServiceFeeBilled
            - AnnualFeeBilled
            - RetailInterestBilled
            - RetailPrincipalUnbilled
            - LateFeeUnbilled
            - CollectionFeeUnbilled
            - RetailMiscFeeUnbilled
            - RetailServiceFeeUnbilled
            - AnnualFeeUnbilled
            - RetailInterestUnbilled
  otherCreditAllocation:
    allocationModel: HIGHESTTOLOWESTAPR
    allocationTieBreaker: REPAYMENTSEQUENCE
    repaymentSequence:
      - chargeOffStatuses:
          - '*'
        repaymentSequenceTieBreaker: FIFO
        settlementPriority:
          - LateFeeBilled
          - CollectionFeeBilled
          - RetailMiscFeeBilled
          - RetailServiceFeeBilled
          - RetailInterestBilled
          - RetailPrincipalBilled
          - LateFeeUnbilled
          - CollectionFeeUnbilled
          - RetailMiscFeeUnbilled
          - RetailServiceFeeUnbilled
          - AnnualFeeUnbilled
          - RetailInterestUnbilled
          - RetailPrincipalUnbilled
      - chargeOffStatuses:
          - FINAL_CHARGEOFF
        repaymentSequenceTieBreaker: FIFO
        settlementPriority:
          - RetailPrincipalBilled
          - LateFeeBilled
          - CollectionFeeBilled
          - RetailMiscFeeBilled
          - RetailServiceFeeBilled
          - RetailInterestBilled
          - RetailPrincipalUnbilled
          - LateFeeUnbilled
          - CollectionFeeUnbilled
          - RetailMiscFeeUnbilled
          - RetailServiceFeeUnbilled
          - AnnualFeeUnbilled
          - RetailInterestUnbilled
  repaymentReversal:
    excessAttributionPostingCategory: RetailPrincipalUnbilled
    lateFeeAdjustment: true
    interestAdjustment: true
  validFrom: '2026-01-01T00:00:00.000+05:30'
  validTill: '2999-12-31T23:59:59.999+05:30'
  templateCode: in-credit
