kind: RubyLateFeePolicy
apiVersion: rrsd.zetaapps.in/v1alpha1
metadata:
  name: lsg.ruby.rubylatefeepolicy.module.8005
  labels:
    rrsd.zetaapps.in/day: day-zero
  annotations:
    zeta.tech/resource-tags: '{"gitDbRepo":"tenant_configuration.aws-clou-upi-pp-mumbai.lsg","gitDbPath":"https://gitea.internal.mum1-pp.zetaapps.in/zetaengg/tenant_configuration.aws-clou-upi-pp-mumbai.lsg.git","filePath":"module_configurations/module_ruby/late-fee-policies/ruby-late-fee-policy_8005.yaml","tenantCode":"lsg"}'
  namespace: ruby
spec:
  metadata:
    id: ruby.rubylatefeepolicy.module.8005
    name: ruby.rubylatefeepolicy.module.8005
    description: ruby.rubylatefeepolicy.module.8005
    tenantId: '600309'
    tenantCode: lsg
  name: Ruby Late Fee Policy
  code: LPFIN00001
  description: Ruby Late Fee Policy
  modelParameters:
    amountType: FIXED
    restrictOnOtherFees: []
    repeatedOccurrence:
      maxAmount: 4100
      baseAmount: 4100
    firstOccurenceAmount:
      maxAmount: 2900
      baseAmount: 2900
    repeatOccurrenceWindow:
      type: CYCLES
      count: '6'
    considerReversedInstances: true
    balanceNotSubjectedToThisFee: []
  chargeStrategy: DIRECT-APPLY
  precedenceCode: ZZ0025
  chargeStrategyConfig:
    placeHold:
      phase: EOPI
      applyOn: keyDateSpecification://code/DUE_DATE
      purposeCode: LATE_PAYMENT_CHARGES
      voucherCode: PLACE_HOLD
      expiryInDays: '100'
    application:
      applyOn: keyDateSpecification://code/GRACE_DATE
      offsetDaysForValueDate: '1'
    releaseHold:
      phase: EOPI
      applyOn: keyDateSpecification://code/BILLING_DATE
      voucherCode: RELEASE_HOLD
  requiredChargeArtifactSummary:
    - categoryCode: LateFeeUnbilled
      duration:
        cycleCode: CYCIN00800501
        unit: MONTHS
        value: 6
      durationType: RELATIVE
  validFrom: '2026-01-01T00:00:00.000-07:00'
  validTill: '2999-12-31T00:00:00.000-07:00'
  templateCode: in-credit

