kind: RubyInterestPolicy
apiVersion: rrsd.zetaapps.in/v1alpha1
metadata:
  name: lsg.ruby.rubyinterestpolicy.upi-interest-policy
  labels:
    rrsd.zetaapps.in/day: day-zero
  namespace: ruby
  annotations:
    zeta.tech/resource-tags: '{"gitDbRepo":"tenant_configuration.aws-upi-pp-mumbai.lsg","gitDbPath":"https://gitea.internal.mum1-pp.zetaapps.in/zetaengg/tenant_configuration.aws-upi-pp-mumbai.lsg.git","filePath":"/.upis/module_configurations/module_ruby/tree/root/t0/module_configurations/module_ruby/ruby-interest-policies/ruby-interest-policy-upi-interest-policy.yaml","tenantCode":"lsg"}'
spec:
  metadata:
    id: ruby.rubyinterestpolicy.upi-interest-policy
    name: upi-interest-policy
    description: upi-interest-policy Ruby upi Interest Policy
    requester:
      module: ruby
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  assessmentParameters:
    computationType: AVGDAILYBALANCEWITHOUTCOMPOUNDING
  code: INTIN0001
  description: upi-interest-policy Ruby UPI Interest Policy
  liquidationParameters:
    dayCountMethod: ACTUAL/ACTUAL
    debitEffectiveFrom: ValueTime
    gracePeriodApplicableOnInterest: true
    interestThreshold: 0
    liquidationModels:
    - balanceType: retail
      billed: WaiveDeferredAndWaiveCurrentIfOpenBalPaidElseBillDeferredAndBillCurrent
      upiRateCard:
        code: IRTUPI00001
        version: '1'
      unBilled: DeferCurrentIfOpenBalPaidElseBillCurrent
    minInterest: 0
    payOffVariance: 0
    paymentPostingCategory: rePayments
    roundingRule: NEAR
    roundingUnit: '2'
  name:  UPI Credit Line Interest Policy
  templateCode: in-credit
  validFrom: 2026-01-01T00:00:00.000+05:30
  validTill: 2999-12-31T23:59:59.999+05:30
