apiVersion: rrsd.zetaapps.in/v1alpha1
kind: RubySpendLimitPolicy
metadata:
  name: lsg.ruby.rubyspendlimitpolicy.default1007
spec:
  metadata:
    id: ruby.rubyspendlimitpolicy.default1007
    name: Default1007 Ruby Spend Limit Policies
    description: Default1007 Ruby Spend Limit Policies
    requester:
      module: ruby-module-e2e
      moduleVersion: 0.0.1
    tenantId: '600309'
    tenantCode: lsg
  validFrom: '2015-07-25T23:09:01.000Z'
  validTill: '2099-07-25T23:09:01.000Z'
  name: Spend Limit Policy 1007
  description: Spend Limit Policy 1007
  code: SPLIN001007
  coaCode: COAIN001007
  disabledForNewCLOU:
    - DOMESTIC_ECOM
  defaultLimitsForNewCLOU:
    - category: DOMESTIC_ECOM
      limitType: PERTRANSACTION
      limitValue: '10000'
  templateCode: in-credit
